<h1 class="text-center"><strong>{{ __('Tutorial') }}</strong></h1><br>


    <h2><strong>{!! __('Usage from the Student Side')!!}</strong></h2>

    <p>
        {!! __('The student has access to two functionalities:')!!}<br>
        {!! __('1. Generating example exercises for solving.')!!}<br>
        {!! __('2. Overview of assigned tasks.')!!}<br>
        {!! __('Therefore, the student can solve examples and submit their solutions.')!!}<br>
        {!! __('The student can choose from which files to generate examples; they can select any one or all of them at once.')!!}<br>
    </p>

    <h2><strong>{!! __('Usage from the Teacher Side')!!}</strong></h2>

    <p>
        {!! __('The teacher has multiple options:')!!}<br>
        {!! __('1. The teacher must insert exercises on the page for students to solve them.')!!}<br>
        {!! __('2. They can assign points to each exercise set.')!!}<br>
        {!! __('3. They can view a clear table of all students with their information, such as name, surname, and student ID.')!!}<br>
        {!! __('   The table also displays the number of exercises generated by each student, the number of exercises submitted, and the points earned for them.')!!}<br>
        {!! __('4. They can generate a table into a CSV file.')!!}<br>
        {!! __('5. They can view how many exercises each student generated, how many they submitted, and the submitted results, including correctness and the points awarded for them.')!!}<br>
    </p>
    <br><br>


